---
- name: Restart akvorado
  community.docker.docker_compose_v2:
    project_src: "{{ _akvorado_project_dir }}"
    profiles: "{{ ['demo'] if akvorado_demo_exporters else omit }}"
    state: restarted
    wait: true
  tags:
    - akvorado
    - docker
