# Copyright 2023 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Run a Sentinel deployment in a local run
  hosts: all
  user: ubuntu
  become: true
  roles:
    - opennms_sentinel
