## file: opennms-playbook.yml

- name: Manage PostgreSQL database
  hosts: database
  become: true
  roles:
    - stub_pgsql

- name: Manage Message broker
  hosts: message-broker
  become: true
  roles:
    - stub_kafka

- name: Manage Elasticsearch
  hosts: elasticsearch
  become: true
  roles:
    - stub_elasticsearch

- name: Manage Mimir
  hosts: mimir
  become: true
  roles:
    - stub_mimir

- name: Manage Grafana
  hosts: grafana
  become: true
  roles:
    - stub_grafana

- name: Manage OpenNMS Horizon Core system
  hosts: core
  become: true
  roles:
    - opennms_core

- name: Manage OpenNMS Horizon Minion
  hosts: minion
  become: true
  roles:
    - opennms_minion

- name: Manage OpenNMS Horizon Sentinel
  hosts: sentinel
  become: true
  roles:
    - opennms_sentinel
