---
- name: Include OpenNMS repository roles
  ansible.builtin.include_role:
    name: opennms_repositories

- name: Installing JICMP
  ansible.builtin.apt:
    name: jicmp={{ jicmp_version }}
    state: present
  tags:
    - opennms
    - icmp

- name: Installing JICMP6
  ansible.builtin.apt:
    name: jicmp6={{ jicmp6_version }}
    state: present
  tags:
    - opennms
    - icmp
