---
- name: Installing OpenJDK {{ openjdk_version }}
  ansible.builtin.apt:
    name: "openjdk-{{ openjdk_version }}-jdk-headless={{ openjdk_pkg_version }}"
    state: present
    install_recommends: false
  tags:
    - opennms
    - java

- name: Set java version to OpenJDK {{ openjdk_version }}
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-{{ openjdk_version }}-openjdk-amd64/bin/java
  tags:
    - opennms
    - java
