---
- name: Installing OpenJDK JDK
  ansible.builtin.apt:
    name: "openjdk-{{ openjdk_version }}-jdk-headless={{ openjdk_pkg_version }}"
    state: present
    install_recommends: false
  tags:
    - java

- name: Set OpenJDK default java version
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-{{ openjdk_version }}-openjdk-amd64/bin/java
  tags:
    - java
