# Copyright 2024 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: GPL-3.0-or-later
---
all:
  children:
    minion:
      children:
        minion:
          hosts:
            minion-01:
              ansible_host: 192.168.10.56
