# {{ ansible_managed }}

# Local configuration options

# ###### DATA COLLECTION ######
# On very large systems the OpenNMS default mechanism of storing one data
# source per RRD file can be very I/O Intensive.  Many I/O subsystems fail
# to keep up with the vast amounts of data that OpenNMS can collect in this
# situation.  We have found that in those situations having fewer large files
# with multiple data sources in each performs better than many smaller files,
# each with a single data source.  This option enables all of the data sources
# belonging to a single collection group to be stored together in a single
# file.  To enable this setting uncomment the below line and change it to
# 'true'.
#
# Default: false
org.opennms.rrd.storeByGroup=true
