---
- name: Include OpenNMS repository roles
  ansible.builtin.include_role:
    name: opennms_repositories

- name: Include OpenNMS OpenJDK roles
  ansible.builtin.include_role:
    name: opennms_openjdk

- name: Include OpenNMS ICMP setup roles
  ansible.builtin.include_role:
    name: opennms_icmp

- name: Include tasks to install packages
  ansible.builtin.include_tasks: 01-packages.yml

- name: Verify if Java configuration exists
  ansible.builtin.stat:
    path: "{{ opennms_home }}/etc/java.conf"
  register: java_conf

- name: Configure Java runtime environment
  become_user: opennms
  ansible.builtin.command: "{{ opennms_home }}/bin/runjava -s"
  changed_when: java_conf
  tags:
    - opennms
    - initialize

- name: Include tasks to setup the database
  ansible.builtin.include_tasks: 10-database-setup.yml

- name: Include tasks configuring the core system
  ansible.builtin.include_tasks: 20-config.yml

- name: Configure Kafka as message broker
  ansible.builtin.include_tasks: 21-kafka.yml
  when: opennms_message_broker == "kafka"

- name: Enable systemd unit for OpenNMS {{ opennms_distribution }}
  ansible.builtin.service:
    name: opennms.service
    enabled: true
  tags:
    - opennms
    - systemd

- name: Start systemd unit for OpenNMS {{ opennms_distribution }}
  ansible.builtin.service:
    name: opennms.service
    state: started
  when:
    - skip_startup | default("false") == "false"
  tags:
    - opennms
    - systemd

- name: Include tasks to configure Firewall rules
  ansible.builtin.include_tasks: 50-firewall.yml
