---
opennms_distribution: Horizon
opennms_version: 32.0.5
opennms_pkg_version: "{{ opennms_version }}*"

opennms_plugin_cloud_version: 1
opennms_plugin_cloud_pkg_version: "{{ opennms_plugin_cloud_version }}.*"
opennms_home: /usr/share/opennms
opennms_message_broker: none

jrrd2_version: 2
jrrd2_pkg_version: "{{ jrrd2_version }}.*"

rrdtool_version: 1
rrdtool_pkg_version: "{{ rrdtool_version }}.*"

iplike_version: 2
iplike_pkg_version: "{{ iplike_version }}.*"

opennms_pkgs:
  - "jrrd2={{ jrrd2_pkg_version }}"
  - "opennms-common={{ opennms_pkg_version }}"
  - "opennms-server={{ opennms_pkg_version }}"
  - "opennms-webapp-jetty={{ opennms_pkg_version }}"
  - "opennms-webapp-hawtio={{ opennms_pkg_version }}"
  - "opennms-plugin-cloud={{ opennms_plugin_cloud_pkg_version }}"

opennms_tool_deps:
  - haveged
  - "rrdtool={{ rrdtool_pkg_version }}"

opennms_perl_deps:
  - libnet-snmp-perl
  - libxml2-utils
  - libwww-perl
  - libxml-twig-perl

opennms_datasource_db_host: localhost
opennms_datasource_db_port: 5432
opennms_datasource_db_name: opennms_horizon

# TODO: Need to go into a secure vault
opennms_datasource_db_user: opennms
opennms_datasource_db_password: p4a55word!

# TODO: Need to go into a secure vault
postgres_user: postgres
postgres_password: oth3rP455w0rd!

opennms_datasource_connection_pool_idle_timeout: 600
opennms_datasource_connection_pool_login_timeout: 3
opennms_datasource_connection_pool_min_pool: 25
opennms_datasource_connection_pool_max_pool: 50
opennms_datasource_connection_pool_max_size: 50
opennms_datasource_opennms_admin_idle_timeout: 600
opennms_datasource_opennms_admin_pool_min: 0
opennms_datasource_opennms_admin_pool_max: 10
opennms_datasource_opennms_admin_pool_max_size: 50
opennms_datasource_opennms_monitor_idle_timeout: 600
opennms_datasource_opennms_monitor_pool_min: 0
opennms_datasource_opennms_monitor_pool_max: 10
opennms_datasource_opennms_monitor_pool_max_size: 50

opennms_jvm_conf:
  # JAVA_INITIAL_HEAP_SIZE: 2048
  # JAVA_HEAP_SIZE: 4096
  PYROSCOPE_AGENT_ENABLED: 0
  PYROSCOPE_APPLICATION_NAME: Horizon-Core
  PYROSCOPE_SERVER_ADDRESS: http://localhost:4040
  # ADDITIONAL_MANAGER_OPTIONS="-javaagent:/usr/share/opennms/lib/jmx_prometheus_javaagent-0.20.0.jar=9299:/usr/share/opennms/etc/jmx-exporter-config.yaml"

opennms_properties_timeseries:
  org.opennms.rrd.strategyClass: org.opennms.netmgt.rrd.rrdtool.MultithreadedJniRrdStrategy
  org.opennms.rrd.interfaceJar: /usr/share/java/jrrd2.jar
  opennms.library.jrrd2: /usr/lib/jni/libjrrd2.so
  org.opennms.web.graphs.engine: rrdtool
  rrd.binary: /usr/bin/rrdtool

opennms_properties_message_broker:
  org.opennms.activemq.broker.disable: true
  org.opennms.core.ipc.strategy: kafka
  org.opennms.core.ipc.sink.initialSleepTime: 60000
  org.opennms.core.ipc.kafka.bootstrap.servers: localhost:9092
