---
- name: Configure time series backend for OpenNMS {{ opennms_distribution }}
  ansible.builtin.template:
    src: etc/opennms.properties.d/_ansible.timeseries.properties.j2
    dest: "{{ opennms_home }}/etc/opennms.properties.d/_ansible.timeseries.properties"
    owner: opennms
    group: opennms
    mode: "0640"
  with_dict: "{{ opennms_properties_timeseries }}"
  notify:
    - Restart opennms
  tags:
    - opennms
    - configuration

- name: Configure webapp for OpenNMS {{ opennms_distribution }}
  ansible.builtin.template:
    src: etc/opennms.properties.d/_ansible.webapp.properties.j2
    dest: "{{ opennms_home }}/etc/opennms.properties.d/_ansible.webapp.properties"
    owner: opennms
    group: opennms
    mode: "0640"
  when: opennms_properties_webapp is defined and opennms_properties_webapp | length > 0
  no_log: true
  notify:
    - Restart opennms
  tags:
    - opennms
    - configuration
    - webapp

- name: Configure Elasticsearch flow persistence for OpenNMS {{ opennms_distribution }}
  ansible.builtin.template:
    src: etc/org.opennms.features.flows.persistence.elastic.cfg.j2
    dest: "{{ opennms_home }}/etc/org.opennms.features.flows.persistence.elastic.cfg"
    owner: opennms
    group: opennms
    mode: "0640"
  when: opennms_elastic_flows is defined and opennms_elastic_flows | length > 0
  no_log: true
  notify:
    - Restart opennms
  tags:
    - opennms
    - configuration
    - elasticsearch

- name: Configure OpenNMS Java Virtual Machine
  ansible.builtin.template:
    src: etc/opennms.conf.j2
    dest: "{{ opennms_home }}/etc/opennms.conf"
    owner: opennms
    group: opennms
    mode: "0640"
  with_dict: "{{ opennms_jvm_conf }}"
  notify:
    - Restart opennms
  tags:
    - opennms
    - openjdk
    - configuration
