# Copyright 2023 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - opennms
    - kafka
    - systemd

- name: Restart kafka
  ansible.builtin.service:
    name: kafka.service
    state: restarted
  tags:
    - opennms
    - kafka
    - systemd
