---
opennms_distribution: Horizon
# renovate: datasource=github-tags depName=OpenNMS/opennms extractVersion=^opennms-(?<version>\d+\.\d+\.\d+)-\d+$
opennms_version: 36.0.0
opennms_pkg_version: "{{ opennms_version }}*"
opennms_minion_home: "/opt/minion"

opennms_minion_controller:
  id: "{{ ansible_facts['machine_id'] if ansible_facts['machine_id'] is defined else inventory_hostname }}"
  location: ANSIBLE_UNSET_MINION_LOCATION

opennms_minion_kafka:
  "bootstrap.servers": localhost:9092
