---
# renovate: datasource=github-releases depName=VictoriaMetrics/VictoriaMetrics
victoriametrics_version: v1.150.0
victoriametrics_arch: amd64
victoriametrics_pkg_url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/victoria-metrics-linux-{{ victoriametrics_arch }}-v{{ victoriametrics_version }}.tar.gz"
victoriametrics_http_port: 8428
victoriametrics_data_path: /var/lib/victoria-metrics
victoriametrics_retention: "1d"
