---
- name: "Set Time Zone to {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "Install dependencies"
  tags: ["system", "tools"]
  ansible.builtin.apt:
    pkg:
      - acl
      - apt-listchanges
      - apt-transport-https
      - bzip2
      - curl
      - git-core
    state: present
