---
pgsql_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
pgsql_key_sha256: 0144068502a1eddd2a0280ede10ef607d1ec592ce819940991203941564e8e76
pgsql_key_ring_file: /usr/share/keyrings/pgsql-keyring.gpg
pgsql_repo_url: https://apt.postgresql.org/pub/repos/apt
arch: amd64
# Just the major version for PostgreSQL, used also for iplike installation and setup
pg_version: 15
pg_pkg_version: "{{ pg_version }}.*"

# TODO: Need to go into a secure vault
postgres_user: postgres
postgres_password: oth3rP455w0rd!
postgres_listen_addresses: localhost
postgres_hba_permissions_v4: 127.0.0.1/32
postgres_hba_permissions_v6: ::1/128
postgres_hba_auth_method: scram-sha-256

# TODO: Need to go into a secure vault
opennms_datasource_db_user: opennms
opennms_datasource_db_password: p4a55word!
opennms_datasource_db_name: opennms_horizon
