# Copyright 2023 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql.service
    state: restarted
  tags:
    - postgresql
    - systemd
