---
- name: Disable ActiveMQ features
  ansible.builtin.copy:
    src: featuresBoot.d/disable-activemq.boot
    dest: "{{ opennms_minion_home }}/etc/featuresBoot.d"
    owner: minion
    group: minion
    mode: '0640'
  notify:
    - Restart minion
  tags:
    - opennms
    - minion
    - configuration

- name: Enable Kafka as a message broker
  ansible.builtin.copy:
    src: featuresBoot.d/message-broker.boot
    dest: "{{ opennms_minion_home }}/etc/featuresBoot.d"
    owner: minion
    group: minion
    mode: '0640'
  notify:
    - Restart minion
  tags:
    - opennms
    - minion
    - configuration
    - kafka

- name: Configure the minion controller
  ansible.builtin.template:
    src: org.opennms.minion.controller.cfg.j2
    dest: "{{ opennms_minion_home }}/etc/org.opennms.minion.controller.cfg"
    owner: minion
    group: minion
    mode: "0640"
  with_dict: "{{ opennms_minion_controller }}"
  notify:
    - Restart minion
  tags:
    - opennms
    - minion
    - configuration
    - kafka

- name: Configure the Kafka message broker
  ansible.builtin.template:
    src: org.opennms.core.ipc.kafka.cfg.j2
    dest: "{{ opennms_minion_home }}/etc/org.opennms.core.ipc.kafka.cfg"
    owner: minion
    group: minion
    mode: "0640"
  with_dict: "{{ opennms_minion_kafka }}"
  notify:
    - Restart minion
  tags:
    - opennms
    - minion
    - configuration
    - kafka
