---
- name: Allow all receiving SNMP traps on port 10162/udp
  community.general.ufw:
    rule: allow
    port: '10162'
    proto: udp
  tags:
    - opennms
    - firewall

- name: Allow all receiving NetFlow protocols on single-port listener on port 9999/udp
  community.general.ufw:
    rule: allow
    port: '9999'
    proto: udp
  tags:
    - opennms
    - firewall
