---
- name: Include OpenNMS OpenJDK roles
  ansible.builtin.include_role:
    name: opennms_openjdk

- name: Include OpenNMS repository roles
  ansible.builtin.include_role:
    name: opennms_repositories

- name: Include OpenNMS ICMP setup roles
  ansible.builtin.include_role:
    name: opennms_icmp

- name: Installing OpenNMS Minion {{ opennms_version }}
  ansible.builtin.apt:
    name: "opennms-minion={{ opennms_pkg_version }}"
    state: present
    install_recommends: false
  tags:
    - opennms
    - minion
    - package

- name: Configure Minion system properties
  ansible.builtin.template:
    src: custom.system.properties.j2
    dest: "{{ opennms_minion_home }}/etc/custom.system.properties"
    owner: minion
    group: minion
    mode: "0640"
  with_dict: "{{ opennms_minion_customer_system_properties }}"
  notify:
    - Restart minion
  tags:
    - opennms
    - minion
    - configuration

# TODO: We need to run the specific role depending on the message broker
- name: Configure Kafka as message broker
  ansible.builtin.include_tasks: 21-kafka.yml

- name: Enable systemd unit for OpenNMS Minion
  ansible.builtin.service:
    name: minion.service
    enabled: true
  tags:
    - opennms
    - minion
    - systemd

- name: Start systemd unit for OpenNMS Minion
  ansible.builtin.service:
    name: minion.service
    state: started
  when:
    - skip_minion_startup | default("false") == "false"
  tags:
    - opennms
    - minion
    - systemd
