# Copyright 2023 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Restart pyroscope
  ansible.builtin.service:
    name: pyroscope.service
    state: restarted
  tags:
    - pyroscope
    - systemd
